### ISSUE TITLE
failed to open apps from Appcake

### ISSUE THREAD

**Issue by shaunstanislaus** [KJCracks/Clutch#100]
I have downloaded your repo 'clutch' from Cydia but it failed to open apps downloaded from Appcake, some apps works without your clutch too, just want to know how to utilise your clutch app, does it mean by having clutch installed via Cydia on iOS 8.3, it should be able to open most apps?

**Comment by NinjaLikesCheez** [comment]
We don't control the AppCake repo, you should talk to them about their repo.

Else, you can download and build the code here :)
