### ISSUE TITLE
Clutch -i crashes for apps installed with ipainstaller

### ISSUE THREAD

**Issue by kotik** [KJCracks/Clutch#101]
iOS 8.4
Clutch RC-5
Clutch works good for apps installed with appstore.
If an app is installed with ipainstaller then:

```
iPad:~ root# ./Clutch -i
2015-07-16 16:32:30.539 Clutch[1144:28068] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[2]'
*** First throw call stack:
(0x2740a137 0x35c81c77 0x27328247 0x2732802b 0xadbd3 0xadf1b 0xbb221 0xbc3ed 0xa1cab 0xa12db 0xbbb01 0x3624faaf)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6
```

**Comment by jalsco** [comment]
Where did you get the RC5 release ? I only got RC4. Did you build it yourself ? Can you make a release of RC5 ??

**Comment by kotik** [comment]
@jalsco I built it for public sources. Not sure if it's supposed to be called RC5. 
Readme.md says "Current version: 2.0-RC5". Probably it is.

**Comment by jalsco** [comment]
Can I get a copy of the the deb file please :))

**Comment by kotik** [comment]
@jalsco Here you are http://www.filedropper.com/ipainstaller

**Comment by jalsco** [comment]
thank u !!!!!!!!

**Comment by kotik** [comment]
@jalsco oops. wrong file)

**Comment by jalsco** [comment]
is that the build of clutch2.ipa

**Comment by jalsco** [comment]
yes I realised that too ;)

**Comment by kotik** [comment]
@jalsco try this one https://yadi.sk/d/brEm8bjthoKvE

**Comment by jalsco** [comment]
thanks :)

**Comment by jalsco** [comment]
i got the file .. but doesn't seem to be a deb file ??

**Comment by jalsco** [comment]
and not an ipa file, not a zip.. what is it ??

**Comment by kotik** [comment]
It's a binary. Use ssh to upload to our jb device. Don't forget to chmod +x

**Comment by jalsco** [comment]
ok

**Comment by jalsco** [comment]
Thanks. I got it running.. Unfortunately for me it does exactly same as RC4. That is, running on ipad-air it gets up to "[line 118] Could not obtain mach port....".   It is an issue that has been rasied several times already so I think well known to the developer. Hopefully there will be an update soon that fixes this problem.

**Comment by kotik** [comment]
Also home so

**Comment by perfaram** [comment]
Clutch dumps binaries from Fairplay DRM-protected IPA. But *aren't IPAInstaller apps already "dumped"* ?

**Comment by Tatsh** [comment]
@perfaram ipainstaller can install your own backed up IPA files (made with iTunes, etc) that have your iCloud account assigned to them. These are still FairPlay protected.

I don't have any cracked apps installed, so I guess someone should test this out with latest HEAD.
