### ISSUE TITLE
/etc/clutch.conf Invalid

### ISSUE THREAD

**Issue by astraylinux** [KJCracks/Clutch#102]
I compiled the latest version of the clutch and had added a `clutch.conf` at `/etc`,  I want to appoint the output directory by  `clutch.conf`, there is the content of my `clutch.conf`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AddMinOS</key>
	<string>NO</string>
	<key>CreditFile</key>
	<string>NO</string>
	<key>IPADirectory</key>
	<string>/tmp/Cracked</string>
	<key>RemoveMetadata</key>
	<string>YES</string>
</dict>
</plist>
```

It doesn't work.

**Comment by ttwj** [comment]
Configurations have been deprecated in Clutch 2, since these features are largely unnecessary today
