### ISSUE TITLE
Failed to dump some app in iOS9

### ISSUE THREAD

**Issue by MTShare** [KJCracks/Clutch#110]
Here is the error:

<b>Error:</b>
ERROR | ARM64Dumper.m:-[ARM64Dumper dumpBinary] [Line 118] | Could not obtain mach port, did you sign with proper entitlements?
sh: line 0: kill: (1082) - No such process
Killed: 9

**Comment by ttwj** [comment]
Which app is this? Thanks

**Comment by MTShare** [comment]
ASK.fm

**Comment by jailbreakiphone** [comment]
Will this be updated soon and will it be able to do frameworks? Thanks!

**Comment by ttwj** [comment]
Yes, hopefully



On Tue, Dec 15, 2015 at 11:44 AM -0800, "jailbreakiphone" <notifications@github.com> wrote:












Will this be updated soon and will it be able to do frameworks? Thanks!

**Comment by jailbreakiphone** [comment]
is getting my hopes up if I ask it for Christmas? :D I'm willing to donate also!

**Comment by ttwj** [comment]
No promises... we'll see!



On Tue, Dec 15, 2015 at 4:37 PM -0800, "jailbreakiphone" <notifications@github.com> wrote:












is getting my hopes up if I ask it for Christmas? :D I'm willing to donate also!

**Comment by warthog3** [comment]
I had trouble cracking another app - Gaia GPS. This is the debug that came out:

![img_1558](https://cloud.githubusercontent.com/assets/4109409/11970399/7559558c-a8e7-11e5-8c65-554782a11bbb.PNG)
![img_1559](https://cloud.githubusercontent.com/assets/4109409/11970397/74801bfa-a8e7-11e5-92d9-be1580f226ac.PNG)
