### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by juneJuly** [KJCracks/Clutch#111]
ERROR:
target specifies product type 'com.apple.product-type.tool', but there's no such product type for the 'iphoneos' platform

iosopendev was installed, but still got this error.

**Comment by juneJuly** [comment]
by the way.
i am work on xcode7 with ios 9

**Comment by easonoutlook** [comment]
Just edit the project.pbxproj, change the com.apple.product-type.tool to com.apple.product-type.application

**Comment by juneJuly** [comment]
@easonoutlook 
u may have miss understand me.

**Comment by mars-rover** [comment]
I had changed the com.apple.product-type.tool to com.apple.product-type.application, But I encountered another build error:
error: Failed to read Info.plist of app /Users/chengjie/Library/Developer/Xcode/DerivedData/Clutch-fqwbzevvvdpnjbakoqbiuogkzccm/Build/Products/Release-iphoneos/Clutch.app (Couldn't load Info dictionary for <DVTFilePath:0x7fa165066580:'/Users/XXX/Library/Developer/Xcode/DerivedData/Clutch-fqwbzevvvdpnjbakoqbiuogkzccm/Build/Products/Release-iphoneos/Clutch.app'>)

**Comment by juneJuly** [comment]
@mars-rover 
trust me.
clutch is just a binary tool instead of an application.
xcode 7 not support iOSOpenDev for now, just use xcode 6, that is a perfect solution.
and it's time to close this issue.
thz

**Comment by mars-rover** [comment]
@juneJuly ok, I trust you, Thanks

**Comment by Tatsh** [comment]
Try the new Makefile. Just run `make` in the `Clutch` directory. `make -j9` (number of cores * 2 + 1) for extra speed. All you need installed is latest Xcode or just the command line tools.
