### ISSUE TITLE
EBADEXEC：posix_spawnp() return 85

### ISSUE THREAD

**Issue by juneJuly** [KJCracks/Clutch#112]
“posix_spawnp (&pid, path, NULL, &attr, NULL, NULL); ”return value is 0x55(85)，which means “EBADEXEC”

how can i fix this?

env: ios8.4 on iPhone5

**Comment by juneJuly** [comment]
maybe we need to check the return value of posix_spawnp() like this:

int err = posix_spawnp (&pid, path, NULL, &attr, NULL, NULL);
if (0 != err) {
    //do something
    return -1;
}

**Comment by juneJuly** [comment]
well, i fix it myself.
Clutch add a runpath to the binary.

that will case a crash when posix_spawnp() is called on ios 8.4, posix_spawnp() return value is 85.

so i just make a little change as below:

- (void)prepareForDump {
    NSLog(@"preparing for dump");
    _executable = [[Binary alloc]initWithBundle:self];
    
    // experimental
    NSMutableData *data = [NSMutableData dataWithContentsOfFile:self.executable.binaryPath];
    
    thin_header headers[4];
    uint32_t numHeaders = 0;
    
    headersFromBinary(headers, data, &numHeaders);
    
    for (int i = 0; i < numHeaders; i++) {
        thin_header _thinHeader = headers[i];
        
        NSString *rpath = self.parentBundle ? [self.parentBundle.bundlePath stringByAppendingPathComponent:@"Frameworks"] : [self.bundlePath stringByAppendingPathComponent:@"Frameworks"] ;
        NSLog(@"checking rpath for %@", self.executable.binaryPath);
        insertRPATHIntoBinary(rpath, data, _thinHeader);
    }
    //=========================FIX CRASH ON IOS8.4=========================== 
    //[data writeToFile:self.executable.binaryPath atomically:YES];
    
    NSDictionary *ownershipInfo = @{NSFileOwnerAccountName:@"mobile", NSFileGroupOwnerAccountName:@"mobile"};
    
    [[NSFileManager defaultManager] setAttributes:ownershipInfo ofItemAtPath:self.executable.binaryPath error:nil];
    
}

**Comment by ttwj** [comment]
thanks
