### ISSUE TITLE
Apps that cannot be dumped

### ISSUE THREAD

**Issue by Tatsh** [KJCracks/Clutch#115]
```
Embark iBART bundleID: 6F68888N5Z.us.pandav.ibart
Lyft bundleID: com.zimride.instant
Venmo bundleID: net.kortina.labs.Venmo
Voyager bundleID: com.linkedin.LinkedIn
XPlay bundleID: com.comcast.cim.xplay
```

**Comment by ttwj** [comment]
Expedia works with the latest commit

**Comment by Tatsh** [comment]
Confirmed and updated original post.

**Comment by iT0ny** [comment]
`
Finished dumping com.apple.store.Jolly in 15.7 seconds
`

**Comment by Tatsh** [comment]
Updated original list.

Also I do not know if you guys care to support `6F68888N5Z.us.pandav.ibart` as the developers are telling their users to stop using their app and use Google Maps. The company was bought out. I predict soon this app will be off the App Store.

**Comment by Tatsh** [comment]
All apps are fixed now that framework dumping works. Tested with latest commit `13065367a5c086def05a1ef6a68cad16bc6341f3` just now.
