### ISSUE TITLE
It's not possible to dump watchOS 2 apps with Clutch 2.0 at this moment.

### ISSUE THREAD

**Issue by haoerloveyou** [KJCracks/Clutch#118]
com.tencent.xin contains watchOS 2 compatible application. It's not possible to dump watchOS 2 apps with Clutch 2.0 at this moment.

waiting u  update :)

**Comment by iT0ny** [comment]
It requires watchOS jailbreak I'm afraid

**Comment by Tatsh** [comment]
@iT0ny have you looked into changing the binary header to be armv7 and cracking it that way? Then maybe put it back to armv7k after?

This will reveal the code if it works, but it will not be loadable on an Apple Watch until there is a jailbreak for that, or at least an unsigned code patch.

From what I can see, LLVM is treating armv7k as armv7 (cortex-a7). Unfortunately I have not been able to find any real information on the difference between armv7k and armv7. It is probably not available for free from ARM yet. Our only hope is the commit log from LLVM it seems.

https://marc.info/?l=llvm-commits&w=2&r=1&s=armv7k&q=b

**Comment by iT0ny** [comment]
@Tatsh yep, tried that already, process gets SIGKILL'ed with no info in syslog/crashlog

**Comment by Tatsh** [comment]
Tried the same and got the same result. When I used LLDB remote debugging, it gave this output on the iPad:

```
./debugserver 0.0.0.0:9000 /private/var/mobile/Containers/Bundle/Application/0FACA3C7-E243-419A-8118-C8B5825C18C7/WeChat.app/Watch/WeChatWatchNative.app/WeChatWatchNativeExtension
debugserver-300.2 for arm64.
error: failed to launch process ./debugserver: Security
Exiting.
```

This is most likely due to a signature mismatch, since the binary is modified yet still hashed and DRM protected. The kernel would have to be patched to ignore this, but who knows if the code will run at that point.

**Comment by qiaoxueshi** [comment]
Is there any solution to delete the native watch app?

**Comment by haoerloveyou** [comment]
rename -ipa to zip.and zip it .enter the folder XXXX.app then delete Watch folder

by haoer
