### ISSUE TITLE
Does not work with native watch app

### ISSUE THREAD

**Issue by qiaoxueshi** [KJCracks/Clutch#123]
If an app contains native watch app, dumped watch app files (XXXWatchNative.app) does not contains native app execution file but only dylib files.
XXX is the name of one app.

```
➜  XXX.app  tree ./Watch
./Watch
└── XXXWatchNative.app
    └── PlugIns
        └── XXXWatchNativeExtension.appex
            └── Frameworks
                ├── libswiftCore.dylib
                ├── libswiftCoreData.dylib
                ├── libswiftCoreGraphics.dylib
                ├── libswiftCoreLocation.dylib
                ├── libswiftDarwin.dylib
                ├── libswiftDispatch.dylib
                ├── libswiftFoundation.dylib
                ├── libswiftObjectiveC.dylib
                ├── libswiftUIKit.dylib
                └── libswiftWatchKit.dylib
```

We know that Clutch works by dumping the memory data of some app to disk, but native watch app does not run in the host iOS system, so Clutch can not dump them to disk. Am I right? any solution for this situation?

**Comment by NinjaLikesCheez** [comment]
Correct. Not yet.

**Comment by Tatsh** [comment]
This is a duplicate of #118

**Comment by qiaoxueshi** [comment]
@Tatsh OK, then.
