### ISSUE TITLE
Some more apps that can not be dumped

### ISSUE THREAD

**Issue by Ka-I-Char** [KJCracks/Clutch#124]
Temple Run <com.imangi.templerun>
FabTap - Tap your hands off <de.finngaida.fabtap>

There are actually more, but the problem looks the same. Those application have two mach-o files in their .app folder. For Temple Run it's TempleRun and TempleRun_armv7. Clutch fails with
Swapping architectures..
Error: Could not obtain mach port, did you sign with proper entitlements?

Tested on iPhone 5s, iOS 9.0.2

**Comment by dibas** [comment]
I am having the same problem with another app, "Taipan!". Executables are named IPan and IPan_armv7, respectively. Output with the debug version is exactly the same as above.

Tested on a 5s, iOS 8.4

**Comment by Tatsh** [comment]
I can test @dibas. Which app is it? App Store shows *Taipan! Mobile*, *Taipan Retro*, a few others.

*FabTap* appears to be protected or there's a bug in Clutch. I can dump other apps fine.

**Comment by dibas** [comment]
Hey. Sorry, I should have clarified that. It's this one: https://itunes.apple.com/us/app/taipan!-mobile/id381945962

**Comment by Tatsh** [comment]
*Taipan! Mobile* has the same problem. I will take a look later for fun. Could it be a new unhandled architecture that lives in the same binary? (tvOS)

**Comment by FlyingNoob** [comment]
I got the same problem. For example appstroe、map of 高德

**Comment by ttwj** [comment]
thanks for your feedback, I'll take a look into them. @FlyingNoob 你指的是https://itunes.apple.com/sg/app/gao-tu-zhuan-ye-shou-ji-tu/id461703208?mt=8码？

**Comment by dibas** [comment]
In case anyone needs it: I managed to dump the binary I needed manually [using LLDB using this tutorial.](http://codedigging.com/blog/2016-03-01-decrypting-apps-from-appstore/) It's a simple workaround until Clutch gets updated.

**Comment by FlyingNoob** [comment]
@ttwj 是的！高德地图，还有天猫。都无法dump

**Comment by ttwj** [comment]
Apologies for the long delay, the bug was caused by our architecture swapping mechanism, which modified the binary excessively and FairPlay began throwing an error.
