### ISSUE TITLE
Build fail in Xcode 7.2

### ISSUE THREAD

**Issue by lin493369** [KJCracks/Clutch#125]
Build fail in Xcode 7.2.
![image](https://cloud.githubusercontent.com/assets/8255169/13593702/acc3d1f4-e538-11e5-8371-defa2a99faa1.png)

**Comment by Tatsh** [comment]
是空白里的文件名。你有文件名`iOS Projects`. 你能有名字`ios-projects`代替.

目前，这个是什么你想：

```bash
git fetch origin pull/126/head:fix125
git checkout fix125
xcodebuild -project Clutch.xcodeproj/ -configuration Release ARCHS="armv7 armv7s arm64" build
```
