### ISSUE TITLE
** BUILD FAILED ** Help~~~

### ISSUE THREAD

**Issue by leungs** [KJCracks/Clutch#128]
Un , when i xcodebuild -project Clutch.xcodeproj -configuration Release ARCHS="armv7 armv7s arm64" build.Something happened:
Linking clutch.unsigned
ld: framework not found AppSupport
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build/clutch.unsigned] Error 1
Command /bin/sh failed with exit code 2

** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution Run\ Script build/Clutch.build/Release-iphoneos/Clutch.build/Script-329B80741C5B6748007DD817.sh
(1 failure)

**Comment by iT0ny** [comment]
Fixed https://github.com/KJCracks/Clutch/commit/1a5ae0326655fcb896493e5a7f1fbe2357fea8cb
