### ISSUE TITLE
Wrong path of binary on iOS 9.3

### ISSUE THREAD

**Issue by hirakujira** [KJCracks/Clutch#136]
Seems that iOS 9.3 changes the app path from /var/mobile/Containers/Bundle/Application/ to /var/containers/Bundle/Application

So the binary won't be inside of the dumped app. Can be fixed by unzip, move the binary and re-zip the ipa.

**Comment by Tatsh** [comment]
What is in the IPA file when dumped originally? It seems unusual that this would affect it. The way apps and their paths are retrieved is via Apple's official APIs and there is no hard-coding of paths.

https://github.com/KJCracks/Clutch/blob/master/Clutch/ApplicationsManager.m#L110

**Comment by hirakujira** [comment]
It looks like this now.

![http://i.imgur.com/CgIabnPg.jpg](http://i.imgur.com/CgIabnPg.jpg)

**Comment by Tatsh** [comment]
Oh, I see. The argument passed to create the zip is the full path to the binary. Normally this is stripped and now with the new location, the replacement string does not match. That would be one of these spots:

https://github.com/KJCracks/Clutch/blob/8bfea9b66b9bdc84ec3d85ceff55ceec03b851c0/Clutch/ZipOperation.m#L104
https://github.com/KJCracks/Clutch/blob/8bfea9b66b9bdc84ec3d85ceff55ceec03b851c0/Clutch/BundleDumpOperation.m#L270

Another line, after the first, would make everything stay compatible:

```objc
NSString *iOS933Path = [theURL.path stringByReplacingOccurrencesOfString:@"/var/mobile/Containers/"
                                                              withString:@"/var/containers/"];
_localPath = [theURL.path stringByReplacingOccurrencesOfString:iOS933Path withString:@""];
```

Not sure which you would have to add this to. I would try both.

**Comment by hirakujira** [comment]
BTW, I'm not sure whether this also occurs on iOS 9.2. Maybe you can check whether "/var/containers/" exists before replacing the path to make sure it works.
