### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by mail2chensh** [KJCracks/Clutch#138]
Hi, I use Clutch 2.0.1 on iPhone 5s, and  iOS 9.0.2 system version. To dump a App name "Tumblr".
But it end with a exception :"Segmentation fault: 11"

and this is the detail informations:

> root# clutch -d com.tumblr.tumblr
> Now dumping com.tumblr.tumblr
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Tumblr
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Analytics.framework/Analytics
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/BRYEqualsBuilder.framework/BRYEqualsBuilder
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/BRYHTMLParser.framework/BRYHTMLParser
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/BRYHashCodeBuilder.framework/BRYHashCodeBuilder
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/BRYMailToURIParser.framework/BRYMailToURIParser
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/BRYParseKeyboardNotification.framework/BRYParseKeyboardNotification
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/BlueLogger.framework/BlueLogger
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Bolts.framework/Bolts
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/CHTCollectionViewWaterfallLayout.framework/CHTCollectionViewWaterfallLayout
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/CocktailsRT.framework/CocktailsRT
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/CocoaLumberjack.framework/CocoaLumberjack
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/ComposeUI.framework/ComposeUI
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/CoreExplore.framework/CoreExplore
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/CoreTumblr.framework/CoreTumblr
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/DataDisplayKit.framework/DataDisplayKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Dwifft.framework/Dwifft
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/ExploreUI.framework/ExploreUI
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/FBSDKCoreKit.framework/FBSDKCoreKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/FBSDKLoginKit.framework/FBSDKLoginKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/FBSDKMessengerShareKit.framework/FBSDKMessengerShareKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/FBSDKShareKit.framework/FBSDKShareKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/GIFCreator.framework/GIFCreator
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/GIFEncoder.framework/GIFEncoder
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/GRMustache.framework/GRMustache
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/JRSwizzle.framework/JRSwizzle
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/JXHTTP.framework/JXHTTP
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/KVOController.framework/KVOController
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Logger.framework/Logger
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Mantle.framework/Mantle
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Messaging.framework/Messaging
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/MessagingSDK.framework/MessagingSDK
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/NetworkAbstractions.framework/NetworkAbstractions
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/OnePasswordExtension.framework/OnePasswordExtension
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/PSPhotoset.framework/PSPhotoset
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/PigeonSDK.framework/PigeonSDK
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/PlaybackAbstractions.framework/PlaybackAbstractions
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/PostAudioView.framework/PostAudioView
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Reachability.framework/Reachability
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/SSKeychain.framework/SSKeychain
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Scimitar.framework/Scimitar
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/ShareExtension.framework/ShareExtension
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/ShareSheet.framework/ShareSheet
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/SharedUI.framework/SharedUI
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/SnoopySDK.framework/SnoopySDK
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/Spectacles.framework/Spectacles
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMAudio.framework/TMAudio
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMCache.framework/TMCache
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMDictionaryUpdatableManagedObject.framework/TMDictionaryUpdatableManagedObject
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMTimelineObject.framework/TMTimelineObject
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMTumblrSDK.framework/TMTumblrSDK
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMTumblrSDK2.framework/TMTumblrSDK2
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TMVideoPlayer.framework/TMVideoPlayer
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TZStackView.framework/TZStackView
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/TakeoverMediaBanner.framework/TakeoverMediaBanner
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/VENTouchLock.framework/VENTouchLock
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/WebViewJavascriptBridge.framework/WebViewJavascriptBridge
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/XExtensionItem.framework/XExtensionItem
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/XMLKit.framework/XMLKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YAccounts.framework/YAccounts
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YAppManagement.framework/YAppManagement
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YFlurrySDK.framework/YFlurrySDK
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YI13N.framework/YI13N
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YLogTelemetry.framework/YLogTelemetry
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YOTeamID.framework/YOTeamID
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YOVeriJSON.framework/YOVeriJSON
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YOWebStringHelpers.framework/YOWebStringHelpers
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YReachability.framework/YReachability
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YRemoteControlSDK.framework/YRemoteControlSDK
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YahooBrowserKit.framework/YahooBrowserKit
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/YahooVideo.framework/YahooVideo
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/sConnectionMonitor.framework/sConnectionMonitor
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/Frameworks/youtube_ios_player_helper.framework/youtube_ios_player_helper
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/PlugIns/Share.appex/Share
> Preparing to dump 
> Path: /private/var/mobile/Containers/Bundle/Application/79FDC8F4-A945-4EAA-85FB-BB4188A07D1F/com.tumblr.Orangina-122-distribution.app/PlugIns/Today.appex/Today
> Zipping com.tumblr.Orangina-122-distribution.app
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | ARMDumper Swapping architectures..
> DUMP | ARMDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> DUMP | FrameworkDumper Swapping architectures..
> Segmentation fault: 11

is there anyone have the same problem?  And anyone know how to solve it?

thank you!

**Comment by mackboudreau** [comment]
I'm having the same issue.

**Comment by mail2chensh** [comment]
@mackboudreau   at last,I use dumpdecrypted to solve this problem.

**Comment by mikeburragejr** [comment]
Try running "ulimit -n 1024" on the command line on the device before running clutch.
It increases the number of allowed open file handles per process.

Code details - I was getting this error when some of the fopen() calls were failing with errno==EMFILE. I'm not sure if there's a file handle leak, or just a lot of open file handles.

**Comment by ttwj** [comment]
Thanks @mikeburragejr! Indeed, there was a serious file handle leak :p Unfortunately, I've been unable to get Tumblr to dump without increasing ulimit, there are simply too many file handles, since Clutch dumps every binary/framework/extension simultaneously. Perhaps we'll have an option to disable multitasking in a future update. For now, `ulimit -n 512` seems to do the trick (the default is 256), Clutch will automatically set the ulimit to 512 when listing apps.
