### ISSUE TITLE
Crack an app

### ISSUE THREAD

**Issue by fegauthier** [KJCracks/Clutch#143]
Hi guys,

I'va crack the app MarcheTaPoutine from the app store (Canada). It works very well. When i used the command line : 

`file marchetapoutine`

I get these informations : 

`marchetapoutine: Mach-O universal binary with 2 architectures: [arm_v7: Mach-O arm_v7 executable] [64-bit architecture=12] []`

After that, i use class-dump-z on the cracked app and i got attribute and method of the program.

Now, i tried to do the same thing with another app. Poule Position 3 (Chicken Run 3) from the apple store too. I did the same thing as MarcheTaPoutine. When i ran the command line : 

`file pouleposition`

I got this : 

`pouleposition: Mach-O 64-bit 64-bit architecture=12 executable`

So, i tried class-dump-z on this cracked app. I got empty files. I retry and i got same thing again. Do i did something wrong ?

Thanks

**Comment by ttwj** [comment]
Could that be a Swift app? class-dump-z has some issues with swift binaries I think, try the latest class-dump https://github.com/nygard/class-dump

**Comment by fegauthier** [comment]
Hi,

Thanks for your answer. I tried with class-dump and it works very well.

Thanks :)
