### ISSUE TITLE
Error: does not contain a matching architecture for specified '-a arm64 394624' option

### ISSUE THREAD

**Issue by wangym324100** [KJCracks/Clutch#149]
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate: input file: XXXXXXXX/XXXXXXXXX does not contain a matching architecture for specified '-a arm64 394624' option
XXXXXXXX/XXXXXXXXX: the codesign_allocate helper tool cannot be found or used

**Comment by NinjaLikesCheez** [comment]
This is a Xcode issue rather than a project issue
