### ISSUE TITLE
Error: Failed to dump <XXX> with arch arm64

### ISSUE THREAD

**Issue by hitgy09** [KJCracks/Clutch#154]
yanteki-iPod-touch:~ root# clutch -d 1
com.alipay.iphoneclient contains watchOS 2 compatible application. It's not possible to dump watchOS 2 apps with Clutch 2.0.4 at this moment.
Zipping AlipayWallet.app
ASLR slide: 0x1000e8000
Dumping <ShareExtension> (arm64)
Patched cryptid (64bit segment)
ASLR slide: 0x100040000
Dumping <APTodayWidget> (arm64)
Patched cryptid (64bit segment)
Writing new checksum
Writing new checksum
Dumping <APIJKPlayer> arm64
Successfully dumped framework APIJKPlayer!
Usage: clutch [OPTIONS]
-b --binary-dump <value> Only dump binary files from specified bundleID 
-d --dump <value>        Dump specified bundleID into .ipa file 
-i --print-installed     Print installed applications 
   --clean               Clean /var/tmp/clutch directory 
   --version             Display version and exit 
-? --help                Display this help and exit 
-n --no-color            Print with colors disabled 

Child exited with status 256
Error: Failed to dump <APIJKPlayer> with arch arm64

2016-12-25 22:35:17.035 clutch[10606:755095] failed operation :(
2016-12-25 22:35:17.037 clutch[10606:755095] application <NSOperationQueue: 0x125638d10>{name = 'NSOperationQueue 0x125638d10'}
Error: Failed to dump <APIJKPlayer>

2016-12-25 22:35:17.037 clutch[10606:755095] failed operation :(
2016-12-25 22:35:17.037 clutch[10606:755095] application <NSOperationQueue: 0x125638d10>{name = 'NSOperationQueue 0x125638d10'}
ASLR slide: 0x100050000
Dumping <AlipayWallet> (arm64)
Patched cryptid (64bit segment)
Writing new checksum
Zipping APIJKPlayer.framework
Zipping APTodayWidget.appex
Zipping ShareExtension.appex
FAILED: <AlipayWallet bundleID: com.alipay.iphoneclient>

**Comment by hitgy09** [comment]
Is it because of there is a dylib/Frameworks in it?  
这是因为里面使用了动态库而无法破解吗？跪求大神解答~~

**Comment by Tatsh** [comment]
Fixed in #155

**Comment by hitgy09** [comment]
Thank You~~

**Comment by hoangpx** [comment]
Still there. 

> iPad:~ root# clutch -d com.yourcompany.DoodleJump
> Zipping DoodleJump.app
> Error: Could not obtain mach port, either the process is dead (codesign error?) or entitlements were not properly signed!
> 
> Error: Failed to dump <DoodleJumpStickersPremium> with arch arm64
> 
> 2016-12-26 19:36:41.409 clutch[3925:360411] failed operation :(
> 2016-12-26 19:36:41.411 clutch[3925:360411] application <NSOperationQueue: 0x13e537380>{name = 'NSOperationQueue 0x13e537380'}
> Error: Failed to dump <DoodleJumpStickersPremium>
> 
> 2016-12-26 19:36:41.411 clutch[3925:360411] failed operation :(
> 2016-12-26 19:36:41.412 clutch[3925:360411] application <NSOperationQueue: 0x13e537380>{name = 'NSOperationQueue 0x13e537380'}
> ASLR slide: 0x1000c4000
> Dumping <DoodleJump> (arm64)
> Patched cryptid (64bit segment)
> Writing new checksum
> Zipping DoodleJumpStickersPremium.appex
> FAILED: <DoodleJump bundleID: com.yourcompany.DoodleJump>
> iPad:~ root# clutch --version
> clutch: version 2.0.4

**Comment by Tatsh** [comment]
That is not this issue. You are running a binary that is either not signed or you need to run `ldid -SClutch.entitlements clutch` (with the file there) on your device to clear the kernel cache.

**Comment by knighthb** [comment]
@hitgy09 你的这个问题解决了么？

**Comment by NSExceptional** [comment]
> That is not this issue. You are running a binary that is either not signed or you need to run `ldid -SClutch.entitlements clutch` (with the file there) on your device to clear the kernel cache.

I built the binary myself, copied it to my device, tried to run it and got the same error. Then tried `ldid -SClutch.entitlements clutch` where `Clutch.entitlements` came from the Xcode project I built the binary from, and where `clutch` was the same binary. Same error.

iOS 9.3.3, tried with Reddit, YouTube, Snapchat, and Twitter. Didn't work for any of them.

**Comment by bensh** [comment]
Just experienced this error myself 

`Error: Failed to dump <UtilsiOS> with arch arm64

2020-01-14 09:55:21.052 Clutch2[2325:43095] failed operation :(
2020-01-14 09:55:21.052 Clutch2[2325:43095] application <NSOperationQueue: 0x100358130>{name = 'NSOperationQueue 0x100358130'}
Error: Failed to dump <UtilsiOS>

2020-01-14 09:55:21.053 Clutch2[2325:43095] failed operation :(
2020-01-14 09:55:21.053 Clutch2[2325:43095] application <NSOperationQueue: 0x100358130>{name = 'NSOperationQueue 0x100358130'}`
