### ISSUE TITLE
Error: Segmentation fault 11

### ISSUE THREAD

**Issue by thebeastgamer25** [KJCracks/Clutch#156]
Yes, I did the fix in the README. Didn't help.

```
Clutch -d com.reddit.Reddit
Zipping Reddit.app
Segmentation fault: 11
```

**Comment by thebeastgamer25** [comment]
oh, also when I use Clutch on your repo I get There are no encrypted applications on this device

**Comment by NinjaLikesCheez** [comment]
Are you running Clutch as root?

**Comment by thebeastgamer25** [comment]
ye

**Comment by thebeastgamer25** [comment]
wait, i fixed it some how. nvm
