### ISSUE TITLE
Code signing is required for product type 'Application' in SDK 'iOS 10.0'

### ISSUE THREAD

**Issue by mgfjxxiexiaolong** [KJCracks/Clutch#160]
'xcodebuild clean build' , this command require code signing in xcode8+, how should i do? singning?

**Comment by Tatsh** [comment]
Please give output from `xcode clean build`.

**Comment by mgfjxxiexiaolong** [comment]
@Tatsh that's it . `Code signing is required for product type 'Application' in SDK 'iOS 10.0'`

**Comment by mgfjxxiexiaolong** [comment]
I signing it with xcode , It works now . @Tatsh

**Comment by NinjaLikesCheez** [comment]
@mgfjxxiexiaolong Have you patched your version of Xcode to bypass code signing restrictions? If you don't want to sign Clutch with a cert through Xcode you'll need to edit these two keys `CODE_SIGNING_REQUIRED` to `NO` and `AD_HOC_CODE_SIGNING_ALLOWED` to `YES` in this file `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist`

**Comment by Tatsh** [comment]
@NinjaLikesCheez need to provide those instructions in the README I guess. Forgot how to do it using plutil or PlistBuddy

**Comment by vesper8** [comment]
I'm having this same problem even though I've run the following commands

```
killall Xcode

/usr/libexec/PlistBuddy -c "Set :DefaultProperties:CODE_SIGNING_REQUIRED NO" /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist\n
/usr/libexec/PlistBuddy -c "Set :DefaultProperties:AD_HOC_CODE_SIGNING_ALLOWED YES" /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist\n

/usr/libexec/PlistBuddy -c "Set :DefaultProperties:CODE_SIGNING_REQUIRED NO" /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/SDKSettings.plist\n
/usr/libexec/PlistBuddy -c "Set :DefaultProperties:AD_HOC_CODE_SIGNING_ALLOWED YES" /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk/SDKSettings.plist\n

 xcodebuild clean build

```

and then I still get

```
=== BUILD TARGET Clutch OF PROJECT Clutch WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
"Clutch" isn't code signed but requires entitlements. It is not possible to add entitlements to a binary without signing it.
Code signing is required for product type 'Application' in SDK 'iOS 10.2'

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

Any help would be appreciated

**Comment by Tatsh** [comment]
I am not getting this error using the instructions and I have the same SDK. Please post a full build log. Also verify manually that `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist` has the correct settings being patched with PlistBuddy.

**Comment by Tatsh** [comment]
```
 $ plutil -p /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/SDKSettings.plist | fgrep SIGNING
    "CODE_SIGNING_REQUIRED" => "NO"
    "AD_HOC_CODE_SIGNING_ALLOWED" => "YES"
```

**Comment by vesper8** [comment]
for some reason PlistBuddy wasn't working unless I ran it as sudo.. now it works

thanks!

**Comment by Tatsh** [comment]
@MelnykTaras Latest commit removes this warning. Clean and rebuild and it should no longer happen.
