### ISSUE TITLE
iOs 10.2 - Compatibility

### ISSUE THREAD

**Issue by BerkanYildiz** [KJCracks/Clutch#163]
![image](https://cloud.githubusercontent.com/assets/15068742/22405773/34291b84-e648-11e6-9799-2978c1a8ba10.png)

**Comment by Tatsh** [comment]
Works here. You need to re-sign that binary. Copy `Clutch/Clutch.entitlements` to your device and resign with `ldid -SClutch.entitlements Clutch`. All this as root. If that works (even if frameworks fail to dump), close this bug. If frameworks fail, that is another issue.

**Comment by Tatsh** [comment]
@NinjaLikesCheez the signing process is not working for 10.2. Have to sign on the device it seems.

**Comment by BerkanYildiz** [comment]
@Tatsh , the binary is dumped (after 22sec), but absolutly unreadable (without signing at least, didn't tried to sign it). On iOs 9, it was working fine, and i was capable to read the binary using IDA Pro.

**Comment by Tatsh** [comment]
@BerkanYildiz That is a different issue. Please open a new ticket for that and the specific application. We are aware several frameworks fail to dump and we are working to figure out why.

**Comment by Tatsh** [comment]
@NinjaLikesCheez I think I may have fixed signing in the most recent commit or I may have copied something wrong. My 10.2 iPad Pro takes the signed binary as is from my computer just fine. Even rebooted to ensure it's not cached in kernel.
