### ISSUE TITLE
zsh: command not found: xcode

### ISSUE THREAD

**Issue by jacinzhang** [KJCracks/Clutch#165]
when I run `xcode clean build`, the terminal show me 
```shell
zsh: command not found: xcode
```

**Comment by alucard0134** [comment]
https://encyclopediadramatica.se/Suicide
consider your options

**Comment by jacinzhang** [comment]
What's fuck?

**Comment by alucard0134** [comment]
oh you're nine also, you must be too young to understand; ask your parents

**Comment by NinjaLikesCheez** [comment]
@alucardo0134 help or fuck off
