### ISSUE TITLE
Xcode couldn't find a provisioning profile matching 'kjc.Clutch'

### ISSUE THREAD

**Issue by jama707** [KJCracks/Clutch#168]
When I try to run `xcodebuild clean build`, I'm getting below error:

```
=== BUILD TARGET Clutch OF PROJECT Clutch WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies
No profiles for 'kjc.Clutch' were found:  Xcode couldn't find a provisioning profile matching 'kjc.Clutch'.

** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

What could be an issue here, I've the latest xcode(Version 8.2.1 (8C1002))

Here's the full log: https://gist.github.com/jama707/d67118af137297e7c089f88b37a02d40

Thanks!

**Comment by Tatsh** [comment]
For now open Xcode and set the developer to yourself. Save the project and quit Xcode. Then you can do the command. It is a tricky issue trying to put a generic signing identity into the project file.

**Comment by Tatsh** [comment]
You must have a paid iOS development account and you must have all your provisiong profiles downloaded onto the computer you are building on. That is: open Xcode, go to *Xcode* menu, *Preferences*, *Accounts* tab, and under your Apple ID click the *View Details* button. You can download provisioning profiles you have set up here, one of which should be the `*` one which will cover any random compile even if you have never opened the project in Xcode before.

<img width="765" alt="screen shot 2017-02-19 at 21 14 54" src="https://cloud.githubusercontent.com/assets/724848/23109653/10e9adda-f6e9-11e6-95e9-42ddb2d44657.png">

**Comment by masbog** [comment]
hi, i didn't find iOS Team Provisioning Profile on xcode 8.3.3, how to solved it?
