### ISSUE TITLE
build error：No profiles for 'kjc.Clutch' were found

### ISSUE THREAD

**Issue by n37r06u3** [KJCracks/Clutch#169]
=== BUILD TARGET Clutch OF PROJECT Clutch WITH CONFIGURATION Release ===

Check dependencies
No profiles for 'kjc.Clutch' were found:  Xcode couldn't find a provisioning profile matching 'kjc.Clutch'.

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by Tatsh** [comment]
This is already answered. Configure your Xcode installation.

https://github.com/KJCracks/Clutch/issues/168#issuecomment-280972316
