### ISSUE TITLE
AppleTV4

### ISSUE THREAD

**Issue by lemonhead94** [KJCracks/Clutch#170]
I'm currently looking into starting to add compatibility for tvOS...

Anything you guys think might be dangerous and I should think twice before running/doing?
Any precautions I can take and can I somehow simulate the behaviour in the simulator, besides the actual decryption which has to take place on the device?

I also don't know yet, how to go about adding the correct "merge effect" since the tvOS apps seem to be split up into these two location:
```
# TopShelf
/private/var/mobile/Containers/Shared/AppGroup/...
# Application
/private/var/mobile/Containers/Data/Application/...
```

**Comment by Tatsh** [comment]
We don't perform disk writes to anywhere except `/Documents/` and `/var/tmp/`, so it should be safe to run the app.

**Comment by Tatsh** [comment]
Please make sure to create a branch in your fork, and then send a PR when you have something that works. However, I don't know if anyone else on the team owns an Apple TV 4 nor would it be easy to find a jailbreakable one.

**Comment by lemonhead94** [comment]
Alright sounds good, I'll be sure to make it on a new branch and send out a PR 👍 
So how did you guys go about debugging your builds, just adding log statements and exiting out early?

**Comment by Tatsh** [comment]
We don't have a great way to debug. I've been trying to figure out how to best debug so we could integrate it with Xcode. We are close to there, given that we have a bundle, but Xcode expects to use its own signed bundle and Xcode will not sign with the correct entitlements we need (it ignores them), which is why we have that as an extra build step.

Otherwise, you should try the [remote debugger](http://iphonedevwiki.net/index.php/Debugserver). Personally I want Xcode's debugger GUI so it can be a little easier.

**Comment by lemonhead94** [comment]
ah thanks I was able to set this up, this should help a lot!

especially something like this will come in handy `(lldb) breakpoint set --file test.c --line 12`

**Comment by linhmui** [comment]
> ah thanks I was able to set this up, this should help a lot!
> especially something like this will come in handy:
> `(lldb) breakpoint set --file test.c --line 12`
> `(lldb) breakpoint set --name "-[NSString stringWithFormat:]"`

Dear
Have any update clutch for tvOS??

Thanks

**Comment by lemonhead94** [comment]
No, not really..
When I was working on this I managed to bootloop/restore my appletv, which caused me to give up on this for now

**Comment by linhmui** [comment]
> No, not really..
> When I was working on this I managed to bootloop/restore my appletv, which caused me to give up on this for now

Can you restart again. Because tvOS 12.2 can be jailbreak with Chimera

Thanks

**Comment by lemonhead94** [comment]
Sadly, I’m on tvOS 12.3 right now...
