### ISSUE TITLE
No profiles for 'kjc.Clutch' were found:  Xcode couldn't find a provisioning profile matching 'kjc.Clutch'.

### ISSUE THREAD

**Issue by JasonZengJ** [KJCracks/Clutch#172]
When I ran ' xcodebuild clean build'  ,I got  this error 

`No profiles for 'kjc.Clutch' were found:  Xcode couldn't find a provisioning profile matching 'kjc.Clutch'.`

**Comment by JasonZengJ** [comment]
How to get the provisioning profile?

**Comment by cuongnv** [comment]
me too, i cant build because of provisioning profile.

**Comment by cuongnv** [comment]
well, i just opened Xcode file and changed bundle ID then i chose personal team in code signing.
Then everything is ok :). i can build nomarly

**Comment by JasonZengJ** [comment]
Thanks a lot!!

**Comment by kidd0** [comment]
Thanks a lot !!!!
