### ISSUE TITLE
Bad CPU type in executable

### ISSUE THREAD

**Issue by karmamaster** [KJCracks/Clutch#181]
Hello,
I have follow the guide on Clutch homepage but somehow my "clutch" executable file not work on my jailbroken iphone (version 8.4). Although this Clutch file is running so well on my macbook. 

Anyone have this problem like me?

Thank you.

**Comment by NinjaLikesCheez** [comment]
Hi, 

Make sure you've selected an iOS target and not a simulator target, you're aiming to build, copy, and run the binary on an iOS device not the MacBook. 

You can use otool or similar to verify the architectures in the binary before copying them over.

**Comment by karmamaster** [comment]
Yah,
I have double check the target is iphone or universal with version 8.0 above. Can you give me more instruction?

**Comment by NinjaLikesCheez** [comment]
I mean the target you're building for, not the target in the project settings. 
<img width="376" alt="screen shot 2017-05-19 at 15 06 08" src="https://cloud.githubusercontent.com/assets/1473041/26251312/c1b9a358-3ca4-11e7-9e07-176341b3c277.png">

**Comment by karmamaster** [comment]
Well, I think that is the simulator which we need to run on. So it affect to the build version too?

**Comment by ttwj** [comment]
The whole point of Clutch is to decrypt applications, which requires it to run on a physical device, since a simulator doesn't have any encrypted applications. Also, Clutch requires root access via jailbreak, which the simulator lacks

**Comment by karmamaster** [comment]
Thanks, I got it! More question, Can I decrypt cydia tweak or tools?

**Comment by Tatsh** [comment]
There is no decrypting of those things. Only FairPlay-protected apps are encrypted.
