### ISSUE TITLE
Is dumping stock apps with clutch possible?

### ISSUE THREAD

**Issue by 916253** [KJCracks/Clutch#182]
Is dumping stock/system apps possible with Clutch? (or is there a similar alternative for that purpose?) I haven't been able to figure out how to do so. Thanks.

**Comment by Tatsh** [comment]
That is not necessary. Once the iOS install is complete the apps are not encrypted in any way. You can verify this by running `strings` (SSH or copy the file locally to your machine) against any stock app's binary and you'll see every string used as opposed to garbage you'd see with FairPlay signed/encrypted apps.

**Comment by 916253** [comment]
Ah yes, I realized this shortly after posting the issue. Sorry about that, my mistake
