### ISSUE TITLE
Hi, I just disabled Xcode code signing, Now Xcode does not open.

### ISSUE THREAD

**Issue by AsimmParvezz** [KJCracks/Clutch#183]
Hi, I just disabled Xcode code singing using the commands provided. Now I get the error "Xcode quit unexpectedly". Can you plese tell me how to reverse it.

**Comment by NinjaLikesCheez** [comment]
Just restore the SDKSettings.plist that you made changes to. Alternatively you could reinstall Xcode, correct changes to SDKSettings.plist should not cause crashes.

**Comment by AsimmParvezz** [comment]
Yes, I had a copy of my Xcode so started using it now.
