### ISSUE TITLE
got “Child exited with status 6/256” error(com.tencent.xin).

### ISSUE THREAD

**Issue by pcSong** [KJCracks/Clutch#192]
Environment：iPhone6、iOS9.3.1、WeChat6.5.13

when Clutch -d 'com.tencent.xin', I got errors as below:
`...
Error: Failed to dump <WCDB> with arch arm64.
Error: Failed to dump <WCDB>...`
`...
Error: Failed to dump <MMCommon> with arch arm64.
Error: Failed to dump <MMCommon>...`
`...
Error: Failed to dump <MultiMedia> with arch arm64.
Error: Failed to dump <MultiMedia>...`
`...
Error: Failed to dump <mars> with arch arm64.
Error: Failed to dump <mars>...`

Anyone can help?
Thx!

**Comment by Tatsh** [comment]
Same as #166
