### ISSUE TITLE
Killed: 9 on iOS 10.2

### ISSUE THREAD

**Issue by leuldereje** [KJCracks/Clutch#200]
Leul:~ root# Clutch2 -d 14
Zipping AnyFont.app
Swapping architectures..
Killed: 9
Leul:~ root#

**Comment by IMcD23** [comment]
You need the platform-application key set to true in the entitlements.plist.

**Comment by leuldereje** [comment]
which " entitlements.plist" are we talking about here coz the app in I am trying to use Clutch2 with doesn't have any "entitilements.plist" in the directories?

**Comment by Epixx512** [comment]
why are you marking everything related to this as closed? maybe instead you could help instead of trying to sweep it under the rug.

**Comment by Epixx512** [comment]
> You need the platform-application key set to true in the entitlements.plist.

which entitlements.plist file are you talking about?
