### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by dannyZhou** [KJCracks/Clutch#206]
git project version: cfe05b9cd1cd5d6834a7f28dcf3fd657b62508e8
xcode version: Version 8.3.3 (8E3004b)
iphone version: 10.2.1 
Build:

```
/Users/danny/git/Clutch/Clutch/ZipOperation.m:95:188: Integer constant not in range of enumerated type 'NSDirectoryEnumerationOptions' (aka 'enum NSDirectoryEnumerationOptions')

/Users/danny/git/Clutch/Clutch/FinalizeDumpOperation.m:87:218: Integer constant not in range of enumerated type 'NSDirectoryEnumerationOptions' (aka 'enum NSDirectoryEnumerationOptions')

/Users/danny/git/Clutch/Clutch/FinalizeDumpOperation.m:137:214: Integer constant not in range of enumerated type 'NSDirectoryEnumerationOptions' (aka 'enum NSDirectoryEnumerationOptions')

```

**Comment by Tatsh** [comment]
This builds with Xcode 9 despite this issue. Please update your version of Xcode.

For all of those lines, replace:

`options:0` 

with

`options:NSDirectoryEnumerationSkipsHiddenFiles`

Will fix later.

**Comment by Tatsh** [comment]
We are not going to support Xcode 8.3.3. Please update to build the project or make the changes above which may not work exactly the same. Xcode 9 fixes this bug and has this in the documentation, showing that the value `0` is allowed now:

> If you wish to only receive the URLs and no other attributes, then pass '0' for 'options' and an empty NSArray ('[NSArray array]') for 'keys'. If you wish to have the property caches of the vended URLs pre-populated with a default set of attributes, then pass '0' for 'options' and 'nil' for 'keys'.
