### ISSUE TITLE
dump binary from terminal on mac?

### ISSUE THREAD

**Issue by JosephShenton** [KJCracks/Clutch#210]
Is it possible to use clutch to dump the binary of an iOS app download from the appstore on mac?

**Comment by Tatsh** [comment]
Not with this project. We don't know of a way to decrypt an iOS app binary without getting it into memory of a jailbroken device. It would be possible on anything else if FairPlay was cracked recently. It is intended to be difficult to crack. It is the one of the few bins (`fairplayd`) on iOS that is partially obfuscated.

[Copy Protection Overview](https://www.theiphonewiki.com/wiki/Copy_Protection_Overview)
