### ISSUE TITLE
crack apps Apple TV 4 

### ISSUE THREAD

**Issue by ADMNTK** [KJCracks/Clutch#215]
Hi guys

How Can I crack the apps Apple TV 4
- version 10.2.2 " jailbreak greeng0blin

Thank You.

**Comment by Tatsh** [comment]
Not supported. Try dump-decrypted

**Comment by Faisal-nz** [comment]
it did work for, i had to install it manually by either downloading/copying the Binary to /usr/bin. Give it the right permission.

**Comment by ADMNTK** [comment]
@Faisal-nz 
شكرا يامطول الغيبة اشتقنا لك زين طلعت 😂
