### ISSUE TITLE
xpc/xpc.h file not found

### ISSUE THREAD

**Issue by ztiandan** [KJCracks/Clutch#23]
When i compile Clutch there is an issue, xpc/xpc.h file not found and i saw below comment  
I use os x 10.9 and ipad mini retina 7.0.4,so i use following code to create link,but it didn't work,could u tell me what i need to do for this issue,thank u.
 ln -s /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/xpc /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS7.1.sdk/usr/include/xpc

**Comment by H0meDev** [comment]
Just copy the required files(xpc.h .etc) to the Xcode SDK folder, it works for me
