### ISSUE TITLE
Unable to find applications signed with an enterprise certificate

### ISSUE THREAD

**Issue by Oh-Py-God** [KJCracks/Clutch#242]
Clutch is unable to find applications signed with an enterprise certificate. 

* iOS version: 10.0.2
* App bundle ID/name: **private**
* Commands used: `Clutch -i` and `Clutch -d bundle.identifier`

Om running `Clutch -i`, I'm not getting the application signed with enterprise certificate.

On running `Clutch -d bundle.identifier`, I get the following message:
```
Couldn't find installed app with bundle identifier: bundle.identifier
```

**Comment by NinjaLikesCheez** [comment]
Unless I'm severely mistaken, apps signed with enterprise certificates are not encrypted.

**Comment by Oh-Py-God** [comment]
You're right @NinjaLikesCheez . The application is not encrypted. I'm actually looking to automate some stuff which involves pulling out the decrypted IPA file from the device.
I want Clutch to list out all installed applications for me. Command: `Clutch -i`

Is there some way out?

**Comment by NinjaLikesCheez** [comment]
If you take a look here you can see how we parse applications: https://github.com/KJCracks/Clutch/blob/master/Clutch/KJApplicationManager.m

You can patch this to list what you need probably.
