### ISSUE TITLE
Clutch start by bundle identifier

### ISSUE THREAD

**Issue by mr-gosh** [KJCracks/Clutch#49]
Clutch can't be started to decrypt an app identified by its "bundle identifier". But this is the only way to recognize a speciffic app - for stable automation right?

**Comment by raymontag** [comment]
@NinjaLikesCheez @Tatsh The method using the installation.plist file doesn't work anymore on iOS 8.x devices as the file doesn't exist on such devices. One could use [AppList](http://iphonedevwiki.net/index.php/AppList) but in many cases it gives a different result than the displayed name in clutch. ATM I use a complicated diff process in my automatic downloader but it isn't the best solution. Do you see the chance to get a more reliable method in future versions of clutch? Or alternatively, do you know a reliable method to get the displayed app name clutch uses? Honestly, I'm not a iOS programmer and don't really understand the way you are using, so I can't copy it.

**Comment by NinjaLikesCheez** [comment]
@raymontag Hi, we use MobileInstallationLookup to get app details. 

Here's a snippet from Clutch to show you what we do:
```
- (NSDictionary *)_allApplications
{   
    NSDictionary* options = @{@"ApplicationType":@"User",
                                                    @"ReturnAttributes":@[@"CFBundleShortVersionString",
                                                    @"CFBundleVersion",
                                                    @"Path",
                                                    @"CFBundleDisplayName",
                                                    @"CFBundleExecutable",
                                                    @"MinimumOSVersion"]};
    
    if (_mobileInstallationLookup) {
        
        NSDictionary *installedApps;
        
        installedApps = _mobileInstallationLookup(options);
    [...]snipped extras[...]
    }
}
```

You can change the `options` to pull out information, I know you're not a programmer but maybe the condensed version will be easier to understand. 

Alternatively you could look at the Info.plist inside the application bundle for all this information too, what Clutch shows you is based on your preferences (unsure about 2.0, I've been really unwell so away for a while) so whichever name you're looking for might change, but have a look at [Core Foundation Keys](https://developer.apple.com/library/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-SW1) for some more information. 

Hopefully that helps, I might be misunderstanding your exact need though - if you need anymore help let me know :)

**Comment by raymontag** [comment]
Thanks for your answer, it seems that this is what I'm looking for :) I'll try to play around with this.
