### ISSUE TITLE
crack fail, ASLR is enabled and we could not identify the decrypted memory region

### ISSUE THREAD

**Issue by lzj0718** [KJCracks/Clutch#75]
I do not install someone app, and scp  the executable file  to the device,run  ./clutch -e path/executable path/executable_new  ,but crack fail, why? How can I do?

DEBUG | Binary.m:1305 | 32-bit mach_vm_error: 1
ASLR is enabled and we could not identify the decrypted memory region.
DEBUG | Binary.m:524 | Failed to dump armv7
Segmentation fault: 11

**Comment by Tatsh** [comment]
Might be a duplicate or related to #81 #79 #73. Basically, Clutch cannot yet crack plugins or extensions.

**Comment by malcolmhall** [comment]
I also has this issue with an app update. Deleting the app and downloading a fresh version fixed it. It might have something to do with the new delta app updates system.

**Comment by Tatsh** [comment]
Good insight. I will be trying this. It would suck that delta updates cause this, because uninstalling an app can make you lose your data for that app (if it does not sync to anywhere) or take a while to re-fetch that data (especially in the case of its `Documents` synced on iCloud).

**Comment by pragyan1994** [comment]
you can remove PIE with removePIE tool, install it from github
