### ISSUE TITLE
Clutch terminating

### ISSUE THREAD

**Issue by bull3tpr00f** [KJCracks/Clutch#78]
Hi, 
i have a major issue with clutch trying to decrypt apps. At some point (mostly after decrypting the first application using "Clutch -a" command) clutch decrypts the first app and terminates after doing so with "Killed: 9". 

When i try to clutch a single app, it soon quits with: 
"Clutch[2395:45535] *** Terminating app due to uncaught exception ´NSRangeException´, reason: ´*** -[__NSArrayM  objectAtIndex:]: index 18446744073709551610 beyond bounds [0 ... 4]

*** First throw call stack: 
(0x188095e48 0x198a980e4 0x187f7b77c 0x1000dd1d8 0x199106a08)
libc++abi.dylib: terminating with uncaught exception of type NSExeption
Abort trap: 6

Could you please help me with this issue? 
Thanks in advance!

**Comment by hhertel** [comment]
System info:
iPad mini 2 wifi
iOS 8.1
Pangu JB
IPA´s loaded with "iMazing"
