### ISSUE TITLE
Using class-dump after clutch

### ISSUE THREAD

**Issue by haniag** [KJCracks/Clutch#83]
This only happens with some apps, and I can't figure out if this is something related to Clutch or class-dump. I get "Error: Cannot find offset for address 0x28000000010048d8 in stringAtAddress:", and when using class-dump-z, I get  "Segmentation fault: 11". Could it be related to app being written in swift? Do you know anyway around it? The specific app I am looking into is "The Guardian". I am using clutch2 B3.

**Comment by iT0ny** [comment]
Yeah, class-dump doesn't work with apps using Swift
