### ISSUE TITLE
Clutch 2.0 RC FAILED:

### ISSUE THREAD

**Issue by Mila432** [KJCracks/Clutch#87]
iPad:~ root# clutch -b com.dena.west.FFRK
Dump |  <ARMDumper: 0x15df54a10> armv7 <Binary: 0x15ded7fb0, executable: DotFFWWToday> swapping archs
Dump |  <ARMDumper: 0x15df54a10> armv7 <Binary: 0x15ded7fb0, executable: DotFFWWToday> wrote new header to binary
Dump |  <ARMDumper: 0x15df54a10> armv7 <Binary: 0x15ded7fb0, executable: DotFFWWToday> 32bit dumping: arch armv7 offset 16384
Dump |  <ARMDumper: 0x15df54a10> armv7 <Binary: 0x15ded7fb0, executable: DotFFWWToday> to MH_PIE or not to MH_PIE, that is the question
Dump |  <ARMDumper: 0x15df54a10> armv7 <Binary: 0x15ded7fb0, executable: DotFFWWToday> ASLR slide: 0x5a000
Finished dumping binary <Binary: 0x15ded7fb0, executable: DotFFWWToday> armv7 with result: 1
Dump |  <ARM64Dumper: 0x15ddceaa0> arm64 <Binary: 0x15ded7fb0, executable: DotFFWWToday> 64bit dumping: arch arm64 offset 81920
Dump |  <ARM64Dumper: 0x15ddceaa0> arm64 <Binary: 0x15ded7fb0, executable: DotFFWWToday> to MH_PIE or not to MH_PIE, that is the question
Dump |  <ARM64Dumper: 0x15ddceaa0> arm64 <Binary: 0x15ded7fb0, executable: DotFFWWToday> ERROR: Could not obtain mach port, did you sign with proper entitlements?
sh: line 0: kill: (24577) - No such process
Failed to dump binary <Binary: 0x15ded7fb0, executable: DotFFWWToday> with arch arm64
Dump |  <ARMDumper: 0x15dedc130> armv7 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> swapping archs
Dump |  <ARMDumper: 0x15dedc130> armv7 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> wrote new header to binary
Dump |  <ARMDumper: 0x15dedc130> armv7 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> 32bit dumping: arch armv7 offset 16384
Dump |  <ARMDumper: 0x15dedc130> armv7 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> to MH_PIE or not to MH_PIE, that is the question
Dump |  <ARMDumper: 0x15dedc130> armv7 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> ASLR slide: 0xbf000
Finished dumping binary <Binary: 0x15dec54d0, executable: DotFFWWMOPS> armv7 with result: 1
Dump |  <ARM64Dumper: 0x15df578c0> arm64 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> 64bit dumping: arch arm64 offset 4194304
Dump |  <ARM64Dumper: 0x15df578c0> arm64 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> to MH_PIE or not to MH_PIE, that is the question
Dump |  <ARM64Dumper: 0x15df578c0> arm64 <Binary: 0x15dec54d0, executable: DotFFWWMOPS> ASLR slide: 0x1000a4000
Finished dumping binary <Binary: 0x15dec54d0, executable: DotFFWWMOPS> arm64 with result: 1
FAILED: <DotFFWWMOPS bundleID: com.dena.west.FFRK>

still have bugs ?

**Comment by Tatsh** [comment]
Just report the bundle ID and/or app name on bug #84

**Comment by Mila432** [comment]
com.dena.west.FFRK https://itunes.apple.com/us/app/final-fantasy-record-keeper/id964320334?mt=8 FINAL FANTASY Record Keeper v3.3.5

**Comment by Tatsh** [comment]
I said to report it on bug #84 not here. It will be a lot easier if failing apps are in one place.

**Comment by ttwj** [comment]
thanks, will check them out
