### ISSUE TITLE
Cannot be built on Xcode 6.3 due to iOSOpenDev incompatibility

### ISSUE THREAD

**Issue by LeoNatan** [KJCracks/Clutch#88]
Hi,

Using Xcode 6.3, it is impossible to build the project due to iOSOpenDev incompatibility.
Please consider providing an additional building solution.

Thanks

**Comment by LeoNatan** [comment]
Hello,

Any news?

**Comment by ttwj** [comment]
We might consider Theos in future, but just downgrade to the old Xcode for now, sorry.
