### ISSUE TITLE
Clutch2 RC2 doesn't output a decrypted binary

### ISSUE THREAD

**Issue by haniag** [KJCracks/Clutch#91]
This is happening with the 3 disney apps (channel, junior, xd). I don't get any errors, but when I try class-dump (or z), it indicates that file is still encrypted. Clutch 1.4.7-2 worked, yet only class-dump worked on it (not z).

EDIT: I was using iPad4,4

**Comment by Tatsh** [comment]
I am not getting this issue. Looking at Google Maps 4.6.0 (which came out recently) in IDA Pro 6.5 and seeing all Objective-C selectors.

**Comment by haniag** [comment]
Yes. This also works for me, and I am not sure why the Disney apps don't. I will try later to open them IDA.
