### ISSUE TITLE
arm64 device can not crack armv7 app

### ISSUE THREAD

**Issue by lzj0718** [KJCracks/Clutch#92]
if use arm64 device to crack the armv7 app，swapping archs，err = task_for_pid(mach_task_self(), pid, &port) will return 1，crack fail and print @"ERROR: Could not obtain mach port, did you sign with proper entitlements?"

**Comment by LeoNatan** [comment]
I am seeing this also.

**Comment by ttwj** [comment]
should've been fixed in RC3, please test and reopen the issue if it persists
