### ISSUE TITLE
I'm wondering whether I can decrypt ipa using a unjailbreak iPhone

### ISSUE THREAD

**Issue by Jeswang** [KJCracks/Clutch#93]
Can I compile the code and run the code in a unjailbreaked iPhone? Put ipa file into the document folder and export ipa into the document folder?

Which function can't I use with out root?

I was trying to add a GUI to Clutch but after I add all the .m files into the GUI target, the App keep crushing and showing this, any idea?

```
#0	0x0210aa97 in __CFTypeCollectionRetain ()
#1	0x0210a8c2 in __CFBasicHashAddValue ()
#2	0x02111df1 in CFBasicHashAddValue ()
#3	0x02151497 in CFDictionaryCreate ()
#4	0x062866cd in BKSHIDEventCreateClientAttributes ()
#5	0x0628673f in ___getHIDEventSystemClient_block_invoke ()
#6	0x031c6bef in _dispatch_client_callout ()
#7	0x031b0a92 in dispatch_once_f ()
#8	0x031b0922 in dispatch_once ()
#9	0x062867ef in BKSHIDEventRegisterEventCallback ()
#10	0x007e5d60 in UIApplicationMain ()
#11	0x000f2b8f in main ()
#12	0x031f2ac9 in start ()
```

**Comment by NinjaLikesCheez** [comment]
You cannot run Clutch on a stock iOS device, the device *has* to be jailbroken in order for this to work.

**Comment by Jeswang** [comment]
@NinjaLikesCheez Can you tell me which function exactly can be used in a stock iOS device?

**Comment by NinjaLikesCheez** [comment]
A lot of them, Clutch has to be run as root, it requires the ability to look at the file system out of the sandbox, and uses private frameworks (among a lot of other things, being able to control processes etc)

Simply put, clutch will not work on a stock iOS device. There are too many functions to be able to tell you exactly which would be able to work on stock iOS, but the dumping will not work.

**Comment by Jeswang** [comment]
Thank you for the details. @NinjaLikesCheez

**Comment by NinjaLikesCheez** [comment]
No problem @JesWang :) here to help
