### ISSUE TITLE
how to debug Clutch?

### ISSUE THREAD

**Issue by mischa07** [KJCracks/Clutch#94]
Hi, Github gods.
the project of Clutch can be compiled. but how to debug it?
When I Command+R to debug it, it show as follow.
"Can't install application
The file at /Users/chenym/Library/Developer/Xcode/DerivedData/Clutch-bqglieeupgcesrcjcuevcqrbupsw/Build/Products/Debug-iphoneos/Clutch is not an ipa file"

**Comment by ttwj** [comment]
it's not an IPA file, you need to copy the deb or the codesigned binary directly to your jailbroken device 



—
