### ISSUE TITLE
Problem with app name containing "Ö"

### ISSUE THREAD

**Issue by AlexanderMalmstrom** [KJCracks/Clutch#95]
I tried to debug an app called Sörmland, ```<Sörmland bundleID: se.infospread.mobitime.r.lts>``` its a Swedish app. I assume the problem is that the app name contains the letter "Ö" because other apps works fine. I'm running the command ```~ root# Clutch2 -d se.infospread.mobitime.r.lts"``` and the output becomes
```
"Dump |  <ARMDumper: 0x176b5700> armv7 <Binary: 0x17536e80, executable: Sörmland>     
32bit dumping: arch armv7 offset 16384
Failed to dump binary <Binary: 0x17536e80, executable: Sörmland> with arch armv7
Failed to dump binary <Binary: 0x17536e80, executable: Sörmland>
FAILED: <Sörmland bundleID: se.infospread.mobitime.r.lts>
```

**Comment by Tatsh** [comment]
This is just a failed dump. I do not think it has to do with the Ö character.

**Comment by AlexanderMalmstrom** [comment]
I see, I see, I assumed it because it worked with another app that did not containing it. But if that is the case, got any tips on how to dump the app?

**Comment by ttwj** [comment]
Could you paste the iTunes link for the app? An upload of the binary would be very useful as well. Sorry about the hiatus on Clutch, all our developers are quite busy and iOS9 would probably break lots of stuff again..

**Comment by AlexanderMalmstrom** [comment]
I totally understand! 
iTunes link: itunes.apple.com/app/lanstrafiken-sormland/id474203519?mt=8
The binary: https://www.dropbox.com/s/oij5p8sw6ui1y8c/938361CE-603D-41EB-B3EF-DFDA0E1C2CB6.zip?dl=0

**Comment by ttwj** [comment]
thanks! :)



—

**Comment by Tatsh** [comment]
@AlexanderMalmstrom try reinstalling the app completely. Delete it and reinstall from the App Store. Failed dumps might be occurring due to the new delta updates system for apps. However I do not recall this many failures back on iOS 6 when delta updates were introduced. How delta updates work probably changes every so often and it is only [documented this much](https://developer.apple.com/library/ios/qa/qa1779/_index.html) for developers (developers do not have to do anything to affect it).

**Comment by AlexanderMalmstrom** [comment]
@Tatsh Just tried it  didn't work :/

**Comment by Tatsh** [comment]
Does the app have any extensions like a Today extension? A Watch extensions? A lot of those fail for me.

But if it does not, that means there is no correlation between the delta update system and ability to dump those. According to Apple, the delta update copies whole files, not binary diffs. So I had my doubts anyway.

**Comment by ttwj** [comment]
this should've been solved in RC3, please check it out and reopen the issue if it persists. thanks!
