### ISSUE TITLE
"Could not obtain mach port"-error...

### ISSUE THREAD

**Issue by raymontag** [KJCracks/Clutch#97]
Found two other apps which produce the "Could not obtain mach port, did you sign with proper entitlements?"-error:

How to Make Origami (com.mobilicos.howtomakeorigami)
Magic Piano (com.smule.minimagicpiano)

Clutch Version is 2.0 RC4

Full output:

DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 30] | preparing for dump
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 45] | checking rpath for /private/var/mobile/Containers/Bundle/Application/6C82A8D2-76D5-43F3-A95B-1E3856764619/How to Make Origami.app/How to Make Origami
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 45] | checking rpath for /private/var/mobile/Containers/Bundle/Application/6C82A8D2-76D5-43F3-A95B-1E3856764619/How to Make Origami.app/How to Make Origami
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 136] | Finding compatible dumper for binary <How to Make Origami> with arch cputype: 12
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 16777228
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 396] | why cut a potato with a pencil?
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 141] | <ARM64Dumper: 0x166b6f90> cannot dump binary <How to Make Origami> (arch armv7). Dumper not compatible, finding another dumper
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 12
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 155] | Found compatible dumper <ARMDumper: 0x165a6680> for binary <How to Make Origami> with arch armv7
DUMP | <ARMDumper: 0x165a6680> armv7 <How to Make Origami> 32bit dumping: arch armv7 offset 16384
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 92] | DUMP: <ARMDumper: 0x165a6680> armv7 <How to Make Origami> FOUND __TEXT SEGMENT
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 82] | DUMP: <ARMDumper: 0x165a6680> armv7 <How to Make Origami> FOUND ENCRYPTION INFO: cryptoff 16384 | cryptsize 1376256 | cryptid 1
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 74] | DUMP: <ARMDumper: 0x165a6680> armv7 <How to Make Origami> FOUND CODE SIGNATURE: dataoff 1640320 | datasize 17952
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 105] | binary path /private/var/mobile/Containers/Bundle/Application/6C82A8D2-76D5-43F3-A95B-1E3856764619/How to Make Origami.app/How to Make Origami
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 113] | DUMP: <ARMDumper: 0x165a6680> armv7 <How to Make Origami> found all required load commands for <How to Make Origami> armv7
DUMP | <ARMDumper: 0x165a6680> armv7 <How to Make Origami> to MH_PIE or not to MH_PIE, that is the question
DEBUG | Dumper.m:-[Dumper posix_spawn:disableASLR:suspend:] [Line 111] | got the pid 2331 /private/var/mobile/Containers/Bundle/Application/6C82A8D2-76D5-43F3-A95B-1E3856764619/How to Make Origami.app/How to Make Origami
ERROR | ARMDumper.m:-[ARMDumper dumpBinary] [Line 123] | Could not obtain mach port, did you sign with proper entitlements?

**Comment by jalsco** [comment]
Here's another one giving the " Could not obtain mach port, did you sign with proper entitlements?" message. It is a free iPad app called VendRegister.  I am running "Clutch2: version 2.0 RC4". 
---
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 30] | preparing for dump
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 45] | checking rpath for /private/var/mobile/Containers/Bundle/Application/18CE0915-DD43-4F16-81B7-D4A178FFE22E/VendRegister.app/VendRegister
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 45] | checking rpath for /private/var/mobile/Containers/Bundle/Application/18CE0915-DD43-4F16-81B7-D4A178FFE22E/VendRegister.app/VendRegister
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 136] | Finding compatible dumper for binary <VendRegister> with arch cputype: 12
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 16777228, cpusubtype: 0
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 16777228
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 396] | why cut a potato with a pencil?
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 141] | <ARM64Dumper: 0x15903eb10> cannot dump binary <VendRegister> (arch armv7). Dumper not compatible, finding another dumper
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 16777228, cpusubtype: 0
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 12
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 401] | cannot use dumper ARMDumper, device not supported
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 141] | <ARMDumper: 0x157f1b650> cannot dump binary <VendRegister> (arch armv7). Dumper not compatible, finding another dumper
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 149] | Couldn't find compatible dumper for binary <VendRegister> with arch armv7. Will have to "strip".
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 150] | offset 16384
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 136] | Finding compatible dumper for binary <VendRegister> with arch cputype: 16777228
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 16777228, cpusubtype: 0
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 16777228, cpusubtype: 0
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 16777228
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 155] | Found compatible dumper <ARM64Dumper: 0x157f1b650> for binary <VendRegister> with arch arm64
DEBUG | ARM64Dumper.m:-[ARM64Dumper dumpBinary] [Line 89] | DUMP: <ARM64Dumper: 0x157f1b650> arm64 <VendRegister> FOUND __TEXT SEGMENT
DEBUG | ARM64Dumper.m:-[ARM64Dumper dumpBinary] [Line 79] | DUMP: <ARM64Dumper: 0x157f1b650> arm64 <VendRegister> FOUND ENCRYPTION INFO: cryptoff 16384 | cryptsize 9748480 | cryptid 1
DEBUG | ARM64Dumper.m:-[ARM64Dumper dumpBinary] [Line 71] | DUMP: <ARM64Dumper: 0x157f1b650> arm64 <VendRegister> FOUND CODE SIGNATURE: dataoff 13156528 | datasize 74592
DEBUG | ARM64Dumper.m:-[ARM64Dumper dumpBinary] [Line 108] | DUMP: <ARM64Dumper: 0x157f1b650> arm64 <VendRegister> found all required load commands for <VendRegister> arm64
DEBUG | Dumper.m:-[Dumper posix_spawn:disableASLR:suspend:] [Line 111] | got the pid 573 /private/var/mobile/Containers/Bundle/Application/18CE0915-DD43-4F16-81B7-D4A178FFE22E/VendRegister.app/VendRegister
ERROR | ARM64Dumper.m:-[ARM64Dumper dumpBinary] [Line 118] | Could not obtain mach port, did you sign with proper entitlements?
sh: line 0: kill: (573) - No such process
ERROR | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 167] | Failed to dump binary <VendRegister> with arch arm64
ERROR | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 174] | Failed to dump binary <VendRegister>
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 5770199488
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 5788374128
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 4201234
DEBUG | FinalizeDumpOperation.m:__30-[FinalizeDumpOperation start]_block_invoke_2 [Line 60] | ending the thread bye bye

**Comment by Snwspeckle** [comment]
I'm experiencing the same problem while trying to decompile.

**Comment by Jake0oo0** [comment]
Can also confirm that I had the same problem trying to decompile an app, Strava I believe it was.
