### ISSUE TITLE
"Dumper not compatible" error

### ISSUE THREAD

**Issue by haniag** [KJCracks/Clutch#98]
Running RC4 on an iPad4,4 iOS 8.3, I get the following log:

**************** BEGIN ****************

iDevice:~ root# Clutch2rc4 -b 5 
Now dumping com.apptao.retinawallpapers

DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 30] | preparing for dump
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 45] | checking rpath for /private/var/mobile/Containers/Bundle/Application/4EDE3DFA-562C-4A4F-AAA6-307689CF425F/9P_RetinaWallpapers.app/9P_RetinaWallpapers
DEBUG | optool-operations.m:BOOL binaryHasRPATH(NSMutableData *__strong, NSString *__strong, uint32_t *, thin_header) [Line 281] | didn't find rpath, no injection!
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 136] | Finding compatible dumper for binary <9P_RetinaWallpapers> with arch cputype: 12
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 16777228, cpusubtype: 0
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 16777228
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 396] | why cut a potato with a pencil?
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 141] | <ARM64Dumper: 0x14f716720> cannot dump binary <9P_RetinaWallpapers> (arch armv7). Dumper not compatible, finding another dumper
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 16777228, cpusubtype: 0
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 12
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 401] | cannot use dumper ARMDumper, device not supported
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 141] | <ARMDumper: 0x14f716720> cannot dump binary <9P_RetinaWallpapers> (arch armv7). Dumper not compatible, finding another dumper
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 149] | Couldn't find compatible dumper for binary <9P_RetinaWallpapers> with arch armv7. Will have to "strip".
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 150] | offset 0
ERROR | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 174] | Failed to dump binary <9P_RetinaWallpapers>
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 5627363424
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 4201234
ERROR | FinalizeDumpOperation.m:-[FinalizeDumpOperation main] [Line 106] | Failed to dump com.apptao.retinawallpapers :(

**************** END ****************

Also, Clutch creates the directory and adds the binary in it, but the binary is still encrypted when running class dump.

**Comment by astraylinux** [comment]
I have the same issue :cry:

**Comment by XieXieZhongxi** [comment]
same issue here，Problem solved？
