### ISSUE TITLE
Clutch 2.0 RC2 & RC4 fail to dump on iOS 8.4

### ISSUE THREAD

**Issue by pahtzo** [KJCracks/Clutch#99]
Latest iOS 8.4 jailbroken using Taig 2.2.0.  Dump log example:

RC2:
Dump |  <ARMDumper: 0x15567a70> armv7 <Binary: 0x1552e710, executable: 2048> 32bit dumping: arch armv7 offset 0
Dump |  <ARMDumper: 0x15567a70> armv7 <Binary: 0x1552e710, executable: 2048> to MH_PIE or not to MH_PIE, that is the question
Dump |  <ARMDumper: 0x15567a70> armv7 <Binary: 0x1552e710, executable: 2048> ERROR: Could not obtain mach port, did you sign with proper entitlements?
sh: line 0: kill: (474) - No such process
Failed to dump binary <Binary: 0x1552e710, executable: 2048> with arch armv7
Failed to dump binary <Binary: 0x1552e710, executable: 2048>
FAILED: <2048 bundleID: com.ketchapp.2048>

RC4:
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 30] | preparing for dump
DEBUG | ClutchBundle.m:-[ClutchBundle prepareForDump] [Line 45] | checking rpath for /private/var/mobile/Containers/Bundle/Application/BCD7DE05-1E1C-4F91-8EF8-84DA0406250D/2048.app/2048
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 136] | Finding compatible dumper for binary <2048> with arch cputype: 12
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 16777228
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 396] | why cut a potato with a pencil?
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 141] | <ARM64Dumper: 0x14e58e30> cannot dump binary <2048> (arch armv7). Dumper not compatible, finding another dumper
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 391] | segment cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 392] | device  cputype: 12, cpusubtype: 9
DEBUG | Dumper.m:-[Dumper compatibilityMode] [Line 393] | dumper supports cputype 12
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 155] | Found compatible dumper <ARMDumper: 0x14d9e3c0> for binary <2048> with arch armv7
DUMP | <ARMDumper: 0x14d9e3c0> armv7 <2048> 32bit dumping: arch armv7 offset 0
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 92] | DUMP: <ARMDumper: 0x14d9e3c0> armv7 <2048> FOUND __TEXT SEGMENT
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 82] | DUMP: <ARMDumper: 0x14d9e3c0> armv7 <2048> FOUND ENCRYPTION INFO: cryptoff 16384 | cryptsize 1474560 | cryptid 1
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 74] | DUMP: <ARMDumper: 0x14d9e3c0> armv7 <2048> FOUND CODE SIGNATURE: dataoff 2392464 | datasize 21584
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 105] | binary path /private/var/mobile/Containers/Bundle/Application/BCD7DE05-1E1C-4F91-8EF8-84DA0406250D/2048.app/2048
DEBUG | ARMDumper.m:-[ARMDumper dumpBinary] [Line 113] | DUMP: <ARMDumper: 0x14d9e3c0> armv7 <2048> found all required load commands for <2048> armv7
DUMP | <ARMDumper: 0x14d9e3c0> armv7 <2048> to MH_PIE or not to MH_PIE, that is the question
DEBUG | Dumper.m:-[Dumper posix_spawn:disableASLR:suspend:] [Line 111] | got the pid 481 /private/var/mobile/Containers/Bundle/Application/BCD7DE05-1E1C-4F91-8EF8-84DA0406250D/2048.app/2048
ERROR | ARMDumper.m:-[ARMDumper dumpBinary] [Line 123] | Could not obtain mach port, did you sign with proper entitlements?
sh: line 0: kill: (481) - No such process
ERROR | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 167] | Failed to dump binary <2048> with arch armv7
ERROR | BundleDumpOperation.m:-[BundleDumpOperation main] [Line 174] | Failed to dump binary <2048>
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 350552896
DEBUG | BundleDumpOperation.m:-[BundleDumpOperation failedOperation] [Line 37] | operation hash 4201234
FAILED: <2048 bundleID: com.ketchapp.2048>
DEBUG | FinalizeDumpOperation.m:__30-[FinalizeDumpOperation start]_block_invoke_2 [Line 60] | ending the thread bye bye
Finished dumping com.ketchapp.2048 in 60.9 seconds

**Comment by aviposs** [comment]
I'm having the exact same problem on iOS 8.3 with TaiG jailbreak

**Comment by jalsco** [comment]
This looks the same as described in other issues (as same as I am getting on 8.4). But  it is with RC4 of the software. The read.me file says it is up to RC5 and there have been 4 commits since the RC4 release. I think the devs have worked on this issue, and it is probably already fixed in RC5.  Does anyone know if RC5 will be built as a Release ?? Then we can test that it runs on armv7 devices on ios8.4 .. Thanks for your great work :)))  but please build a release soon

**Comment by Tatsh** [comment]
Yeah I have not had a successful dump of an app in a while.

**Comment by pahtzo** [comment]
Closing as this issue is well covered now in #103 https://github.com/KJCracks/Clutch/issues/103
